development:
  devise_key: e6a08a8908146cdb0de140c35fa97c039197407e9bee6d1db02cf93cdae44fc931e46717aafc35fc0bb79a183b8ac634b99a3fdbe64df911dddbf0157bebb925
  secret_key_base: 1cf3d43d206f19a51542ca9900519fa0d69504d9ec7211151c16d2cfb7e7de8432db26443b86d254ff228a6fb77cab8f7e0a919ca27adeedd089ebca716d2e44

  facebook_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_id: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>

test:
  devise_key: testmcphee
  secret_key_base: testkey

  facebook_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_id: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>

production:
  devise_key: <%= ENV["DEVISE_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  facebook_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_id: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
